export enum InteractionCallbackType {
    PONG = 1,
    ACKNOWLEDGE = 2, // Deprecated
    CHANNEL_MESSAGE = 3, // Deprecated
    CHANNEL_MESSAGE_WITH_SOURCE = 4,
    DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5,
    DEFERRED_UPDATE_MESSAGE = 6,
    UPDATE_MESSAGE = 7,
    APPLICATION_COMMAND_AUTOCOMPLETE_RESULT = 8,
    MODAL = 9,
    PREMIUM_REQUIRED = 10, // Deprecated
    IFRAME_MODAL = 11,
    LAUNCH_ACTIVITY = 12,
}
