import { MigrationInterface, QueryRunner } from "typeorm";

export class mobileFixes21660689586029 implements MigrationInterface {
    name = 'mobileFixes21660689586029'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "temporary_channels" (
                "id" varchar PRIMARY KEY NOT NULL,
                "created_at" datetime NOT NULL,
                "name" varchar,
                "icon" text,
                "type" integer NOT NULL,
                "last_message_id" varchar,
                "guild_id" varchar,
                "parent_id" varchar,
                "owner_id" varchar,
                "last_pin_timestamp" integer,
                "default_auto_archive_duration" integer,
                "position" integer,
                "permission_overwrites" text,
                "video_quality_mode" integer,
                "bitrate" integer,
                "user_limit" integer,
                "nsfw" boolean,
                "rate_limit_per_user" integer,
                "topic" varchar,
                "retention_policy_id" varchar,
                "flags" integer,
                "default_thread_rate_limit_per_user" integer,
                CONSTRAINT "FK_c253dafe5f3a03ec00cd8fb4581" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
                CONSTRAINT "FK_3274522d14af40540b1a883fc80" FOREIGN KEY ("parent_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_3873ed438575cce703ecff4fc7b" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_channels"(
                    "id",
                    "created_at",
                    "name",
                    "icon",
                    "type",
                    "last_message_id",
                    "guild_id",
                    "parent_id",
                    "owner_id",
                    "last_pin_timestamp",
                    "default_auto_archive_duration",
                    "position",
                    "permission_overwrites",
                    "video_quality_mode",
                    "bitrate",
                    "user_limit",
                    "nsfw",
                    "rate_limit_per_user",
                    "topic",
                    "retention_policy_id",
                    "flags",
                    "default_thread_rate_limit_per_user"
                )
            SELECT "id",
                "created_at",
                "name",
                "icon",
                "type",
                "last_message_id",
                "guild_id",
                "parent_id",
                "owner_id",
                "last_pin_timestamp",
                "default_auto_archive_duration",
                "position",
                "permission_overwrites",
                "video_quality_mode",
                "bitrate",
                "user_limit",
                "nsfw",
                "rate_limit_per_user",
                "topic",
                "retention_policy_id",
                "flags",
                "default_thread_rate_limit_per_user"
            FROM "channels"
        `);
        await queryRunner.query(`
            DROP TABLE "channels"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_channels"
                RENAME TO "channels"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_guilds" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_channel_id" varchar,
                "afk_timeout" integer,
                "banner" varchar,
                "default_message_notifications" integer,
                "description" varchar,
                "discovery_splash" varchar,
                "explicit_content_filter" integer,
                "features" text NOT NULL,
                "primary_category_id" integer,
                "icon" varchar,
                "large" boolean,
                "max_members" integer,
                "max_presences" integer,
                "max_video_channel_users" integer,
                "member_count" integer,
                "presence_count" integer,
                "template_id" varchar,
                "mfa_level" integer,
                "name" varchar NOT NULL,
                "owner_id" varchar,
                "preferred_locale" varchar,
                "premium_subscription_count" integer,
                "premium_tier" integer,
                "public_updates_channel_id" varchar,
                "rules_channel_id" varchar,
                "region" varchar,
                "splash" varchar,
                "system_channel_id" varchar,
                "system_channel_flags" integer,
                "unavailable" boolean,
                "verification_level" integer,
                "welcome_screen" text NOT NULL,
                "widget_channel_id" varchar,
                "widget_enabled" boolean,
                "nsfw_level" integer,
                "nsfw" boolean,
                "parent" varchar,
                "premium_progress_bar_enabled" boolean,
                CONSTRAINT "FK_9d1d665379eefde7876a17afa99" FOREIGN KEY ("widget_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_cfc3d3ad260f8121c95b31a1fce" FOREIGN KEY ("system_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_95828668aa333460582e0ca6396" FOREIGN KEY ("rules_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_8d450b016dc8bec35f36729e4b0" FOREIGN KEY ("public_updates_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_fc1a451727e3643ca572a3bb394" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_e2a2f873a64a5cf62526de42325" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_f591a66b8019d87b0fe6c12dad6" FOREIGN KEY ("afk_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_guilds"(
                    "id",
                    "afk_channel_id",
                    "afk_timeout",
                    "banner",
                    "default_message_notifications",
                    "description",
                    "discovery_splash",
                    "explicit_content_filter",
                    "features",
                    "primary_category_id",
                    "icon",
                    "large",
                    "max_members",
                    "max_presences",
                    "max_video_channel_users",
                    "member_count",
                    "presence_count",
                    "template_id",
                    "mfa_level",
                    "name",
                    "owner_id",
                    "preferred_locale",
                    "premium_subscription_count",
                    "premium_tier",
                    "public_updates_channel_id",
                    "rules_channel_id",
                    "region",
                    "splash",
                    "system_channel_id",
                    "system_channel_flags",
                    "unavailable",
                    "verification_level",
                    "welcome_screen",
                    "widget_channel_id",
                    "widget_enabled",
                    "nsfw_level",
                    "nsfw",
                    "parent",
                    "premium_progress_bar_enabled"
                )
            SELECT "id",
                "afk_channel_id",
                "afk_timeout",
                "banner",
                "default_message_notifications",
                "description",
                "discovery_splash",
                "explicit_content_filter",
                "features",
                "primary_category_id",
                "icon",
                "large",
                "max_members",
                "max_presences",
                "max_video_channel_users",
                "member_count",
                "presence_count",
                "template_id",
                "mfa_level",
                "name",
                "owner_id",
                "preferred_locale",
                "premium_subscription_count",
                "premium_tier",
                "public_updates_channel_id",
                "rules_channel_id",
                "region",
                "splash",
                "system_channel_id",
                "system_channel_flags",
                "unavailable",
                "verification_level",
                "welcome_screen",
                "widget_channel_id",
                "widget_enabled",
                "nsfw_level",
                "nsfw",
                "parent",
                "premium_progress_bar_enabled"
            FROM "guilds"
        `);
        await queryRunner.query(`
            DROP TABLE "guilds"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_guilds"
                RENAME TO "guilds"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_user_settings" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_timeout" integer,
                "allow_accessibility_detection" boolean,
                "animate_emoji" boolean,
                "animate_stickers" integer,
                "contact_sync_enabled" boolean,
                "convert_emoticons" boolean,
                "custom_status" text,
                "default_guilds_restricted" boolean,
                "detect_platform_accounts" boolean,
                "developer_mode" boolean,
                "disable_games_tab" boolean,
                "enable_tts_command" boolean,
                "explicit_content_filter" integer,
                "friend_source_flags" text,
                "gateway_connected" boolean,
                "gif_auto_play" boolean,
                "guild_folders" text,
                "guild_positions" text,
                "inline_attachment_media" boolean,
                "inline_embed_media" boolean,
                "locale" varchar,
                "message_display_compact" boolean,
                "native_phone_integration_enabled" boolean,
                "render_embeds" boolean,
                "render_reactions" boolean,
                "restricted_guilds" text,
                "show_current_game" boolean,
                "status" varchar,
                "stream_notifications_enabled" boolean,
                "theme" varchar,
                "timezone_offset" integer,
                "friend_discovery_flags" integer NOT NULL,
                "view_nsfw_guilds" boolean NOT NULL,
                "passwordless" boolean NOT NULL,
                "banner_color" varchar
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_user_settings"(
                    "id",
                    "afk_timeout",
                    "allow_accessibility_detection",
                    "animate_emoji",
                    "animate_stickers",
                    "contact_sync_enabled",
                    "convert_emoticons",
                    "custom_status",
                    "default_guilds_restricted",
                    "detect_platform_accounts",
                    "developer_mode",
                    "disable_games_tab",
                    "enable_tts_command",
                    "explicit_content_filter",
                    "friend_source_flags",
                    "gateway_connected",
                    "gif_auto_play",
                    "guild_folders",
                    "guild_positions",
                    "inline_attachment_media",
                    "inline_embed_media",
                    "locale",
                    "message_display_compact",
                    "native_phone_integration_enabled",
                    "render_embeds",
                    "render_reactions",
                    "restricted_guilds",
                    "show_current_game",
                    "status",
                    "stream_notifications_enabled",
                    "theme",
                    "timezone_offset",
                    "friend_discovery_flags",
                    "view_nsfw_guilds",
                    "passwordless"
                )
            SELECT "id",
                "afk_timeout",
                "allow_accessibility_detection",
                "animate_emoji",
                "animate_stickers",
                "contact_sync_enabled",
                "convert_emoticons",
                "custom_status",
                "default_guilds_restricted",
                "detect_platform_accounts",
                "developer_mode",
                "disable_games_tab",
                "enable_tts_command",
                "explicit_content_filter",
                "friend_source_flags",
                "gateway_connected",
                "gif_auto_play",
                "guild_folders",
                "guild_positions",
                "inline_attachment_media",
                "inline_embed_media",
                "locale",
                "message_display_compact",
                "native_phone_integration_enabled",
                "render_embeds",
                "render_reactions",
                "restricted_guilds",
                "show_current_game",
                "status",
                "stream_notifications_enabled",
                "theme",
                "timezone_offset",
                "friend_discovery_flags",
                "view_nsfw_guilds",
                "passwordless"
            FROM "user_settings"
        `);
        await queryRunner.query(`
            DROP TABLE "user_settings"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_user_settings"
                RENAME TO "user_settings"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_channels" (
                "id" varchar PRIMARY KEY NOT NULL,
                "created_at" datetime NOT NULL,
                "name" varchar,
                "icon" text,
                "type" integer NOT NULL,
                "last_message_id" varchar,
                "guild_id" varchar,
                "parent_id" varchar,
                "owner_id" varchar,
                "last_pin_timestamp" integer,
                "default_auto_archive_duration" integer,
                "position" integer,
                "permission_overwrites" text,
                "video_quality_mode" integer,
                "bitrate" integer,
                "user_limit" integer,
                "nsfw" boolean NOT NULL,
                "rate_limit_per_user" integer,
                "topic" varchar,
                "retention_policy_id" varchar,
                "flags" integer,
                "default_thread_rate_limit_per_user" integer,
                CONSTRAINT "FK_c253dafe5f3a03ec00cd8fb4581" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
                CONSTRAINT "FK_3274522d14af40540b1a883fc80" FOREIGN KEY ("parent_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_3873ed438575cce703ecff4fc7b" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_channels"(
                    "id",
                    "created_at",
                    "name",
                    "icon",
                    "type",
                    "last_message_id",
                    "guild_id",
                    "parent_id",
                    "owner_id",
                    "last_pin_timestamp",
                    "default_auto_archive_duration",
                    "position",
                    "permission_overwrites",
                    "video_quality_mode",
                    "bitrate",
                    "user_limit",
                    "nsfw",
                    "rate_limit_per_user",
                    "topic",
                    "retention_policy_id",
                    "flags",
                    "default_thread_rate_limit_per_user"
                )
            SELECT "id",
                "created_at",
                "name",
                "icon",
                "type",
                "last_message_id",
                "guild_id",
                "parent_id",
                "owner_id",
                "last_pin_timestamp",
                "default_auto_archive_duration",
                "position",
                "permission_overwrites",
                "video_quality_mode",
                "bitrate",
                "user_limit",
                "nsfw",
                "rate_limit_per_user",
                "topic",
                "retention_policy_id",
                "flags",
                "default_thread_rate_limit_per_user"
            FROM "channels"
        `);
        await queryRunner.query(`
            DROP TABLE "channels"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_channels"
                RENAME TO "channels"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_guilds" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_channel_id" varchar,
                "afk_timeout" integer,
                "banner" varchar,
                "default_message_notifications" integer,
                "description" varchar,
                "discovery_splash" varchar,
                "explicit_content_filter" integer,
                "features" text NOT NULL,
                "primary_category_id" integer,
                "icon" varchar,
                "large" boolean,
                "max_members" integer,
                "max_presences" integer,
                "max_video_channel_users" integer,
                "member_count" integer,
                "presence_count" integer,
                "template_id" varchar,
                "mfa_level" integer,
                "name" varchar NOT NULL,
                "owner_id" varchar,
                "preferred_locale" varchar,
                "premium_subscription_count" integer,
                "premium_tier" integer,
                "public_updates_channel_id" varchar,
                "rules_channel_id" varchar,
                "region" varchar,
                "splash" varchar,
                "system_channel_id" varchar,
                "system_channel_flags" integer,
                "unavailable" boolean,
                "verification_level" integer,
                "welcome_screen" text NOT NULL,
                "widget_channel_id" varchar,
                "widget_enabled" boolean,
                "nsfw_level" integer,
                "nsfw" boolean NOT NULL,
                "parent" varchar,
                "premium_progress_bar_enabled" boolean,
                CONSTRAINT "FK_9d1d665379eefde7876a17afa99" FOREIGN KEY ("widget_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_cfc3d3ad260f8121c95b31a1fce" FOREIGN KEY ("system_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_95828668aa333460582e0ca6396" FOREIGN KEY ("rules_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_8d450b016dc8bec35f36729e4b0" FOREIGN KEY ("public_updates_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_fc1a451727e3643ca572a3bb394" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_e2a2f873a64a5cf62526de42325" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_f591a66b8019d87b0fe6c12dad6" FOREIGN KEY ("afk_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_guilds"(
                    "id",
                    "afk_channel_id",
                    "afk_timeout",
                    "banner",
                    "default_message_notifications",
                    "description",
                    "discovery_splash",
                    "explicit_content_filter",
                    "features",
                    "primary_category_id",
                    "icon",
                    "large",
                    "max_members",
                    "max_presences",
                    "max_video_channel_users",
                    "member_count",
                    "presence_count",
                    "template_id",
                    "mfa_level",
                    "name",
                    "owner_id",
                    "preferred_locale",
                    "premium_subscription_count",
                    "premium_tier",
                    "public_updates_channel_id",
                    "rules_channel_id",
                    "region",
                    "splash",
                    "system_channel_id",
                    "system_channel_flags",
                    "unavailable",
                    "verification_level",
                    "welcome_screen",
                    "widget_channel_id",
                    "widget_enabled",
                    "nsfw_level",
                    "nsfw",
                    "parent",
                    "premium_progress_bar_enabled"
                )
            SELECT "id",
                "afk_channel_id",
                "afk_timeout",
                "banner",
                "default_message_notifications",
                "description",
                "discovery_splash",
                "explicit_content_filter",
                "features",
                "primary_category_id",
                "icon",
                "large",
                "max_members",
                "max_presences",
                "max_video_channel_users",
                "member_count",
                "presence_count",
                "template_id",
                "mfa_level",
                "name",
                "owner_id",
                "preferred_locale",
                "premium_subscription_count",
                "premium_tier",
                "public_updates_channel_id",
                "rules_channel_id",
                "region",
                "splash",
                "system_channel_id",
                "system_channel_flags",
                "unavailable",
                "verification_level",
                "welcome_screen",
                "widget_channel_id",
                "widget_enabled",
                "nsfw_level",
                "nsfw",
                "parent",
                "premium_progress_bar_enabled"
            FROM "guilds"
        `);
        await queryRunner.query(`
            DROP TABLE "guilds"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_guilds"
                RENAME TO "guilds"
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "guilds"
                RENAME TO "temporary_guilds"
        `);
        await queryRunner.query(`
            CREATE TABLE "guilds" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_channel_id" varchar,
                "afk_timeout" integer,
                "banner" varchar,
                "default_message_notifications" integer,
                "description" varchar,
                "discovery_splash" varchar,
                "explicit_content_filter" integer,
                "features" text NOT NULL,
                "primary_category_id" integer,
                "icon" varchar,
                "large" boolean,
                "max_members" integer,
                "max_presences" integer,
                "max_video_channel_users" integer,
                "member_count" integer,
                "presence_count" integer,
                "template_id" varchar,
                "mfa_level" integer,
                "name" varchar NOT NULL,
                "owner_id" varchar,
                "preferred_locale" varchar,
                "premium_subscription_count" integer,
                "premium_tier" integer,
                "public_updates_channel_id" varchar,
                "rules_channel_id" varchar,
                "region" varchar,
                "splash" varchar,
                "system_channel_id" varchar,
                "system_channel_flags" integer,
                "unavailable" boolean,
                "verification_level" integer,
                "welcome_screen" text NOT NULL,
                "widget_channel_id" varchar,
                "widget_enabled" boolean,
                "nsfw_level" integer,
                "nsfw" boolean,
                "parent" varchar,
                "premium_progress_bar_enabled" boolean,
                CONSTRAINT "FK_9d1d665379eefde7876a17afa99" FOREIGN KEY ("widget_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_cfc3d3ad260f8121c95b31a1fce" FOREIGN KEY ("system_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_95828668aa333460582e0ca6396" FOREIGN KEY ("rules_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_8d450b016dc8bec35f36729e4b0" FOREIGN KEY ("public_updates_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_fc1a451727e3643ca572a3bb394" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_e2a2f873a64a5cf62526de42325" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_f591a66b8019d87b0fe6c12dad6" FOREIGN KEY ("afk_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "guilds"(
                    "id",
                    "afk_channel_id",
                    "afk_timeout",
                    "banner",
                    "default_message_notifications",
                    "description",
                    "discovery_splash",
                    "explicit_content_filter",
                    "features",
                    "primary_category_id",
                    "icon",
                    "large",
                    "max_members",
                    "max_presences",
                    "max_video_channel_users",
                    "member_count",
                    "presence_count",
                    "template_id",
                    "mfa_level",
                    "name",
                    "owner_id",
                    "preferred_locale",
                    "premium_subscription_count",
                    "premium_tier",
                    "public_updates_channel_id",
                    "rules_channel_id",
                    "region",
                    "splash",
                    "system_channel_id",
                    "system_channel_flags",
                    "unavailable",
                    "verification_level",
                    "welcome_screen",
                    "widget_channel_id",
                    "widget_enabled",
                    "nsfw_level",
                    "nsfw",
                    "parent",
                    "premium_progress_bar_enabled"
                )
            SELECT "id",
                "afk_channel_id",
                "afk_timeout",
                "banner",
                "default_message_notifications",
                "description",
                "discovery_splash",
                "explicit_content_filter",
                "features",
                "primary_category_id",
                "icon",
                "large",
                "max_members",
                "max_presences",
                "max_video_channel_users",
                "member_count",
                "presence_count",
                "template_id",
                "mfa_level",
                "name",
                "owner_id",
                "preferred_locale",
                "premium_subscription_count",
                "premium_tier",
                "public_updates_channel_id",
                "rules_channel_id",
                "region",
                "splash",
                "system_channel_id",
                "system_channel_flags",
                "unavailable",
                "verification_level",
                "welcome_screen",
                "widget_channel_id",
                "widget_enabled",
                "nsfw_level",
                "nsfw",
                "parent",
                "premium_progress_bar_enabled"
            FROM "temporary_guilds"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_guilds"
        `);
        await queryRunner.query(`
            ALTER TABLE "channels"
                RENAME TO "temporary_channels"
        `);
        await queryRunner.query(`
            CREATE TABLE "channels" (
                "id" varchar PRIMARY KEY NOT NULL,
                "created_at" datetime NOT NULL,
                "name" varchar,
                "icon" text,
                "type" integer NOT NULL,
                "last_message_id" varchar,
                "guild_id" varchar,
                "parent_id" varchar,
                "owner_id" varchar,
                "last_pin_timestamp" integer,
                "default_auto_archive_duration" integer,
                "position" integer,
                "permission_overwrites" text,
                "video_quality_mode" integer,
                "bitrate" integer,
                "user_limit" integer,
                "nsfw" boolean,
                "rate_limit_per_user" integer,
                "topic" varchar,
                "retention_policy_id" varchar,
                "flags" integer,
                "default_thread_rate_limit_per_user" integer,
                CONSTRAINT "FK_c253dafe5f3a03ec00cd8fb4581" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
                CONSTRAINT "FK_3274522d14af40540b1a883fc80" FOREIGN KEY ("parent_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_3873ed438575cce703ecff4fc7b" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "channels"(
                    "id",
                    "created_at",
                    "name",
                    "icon",
                    "type",
                    "last_message_id",
                    "guild_id",
                    "parent_id",
                    "owner_id",
                    "last_pin_timestamp",
                    "default_auto_archive_duration",
                    "position",
                    "permission_overwrites",
                    "video_quality_mode",
                    "bitrate",
                    "user_limit",
                    "nsfw",
                    "rate_limit_per_user",
                    "topic",
                    "retention_policy_id",
                    "flags",
                    "default_thread_rate_limit_per_user"
                )
            SELECT "id",
                "created_at",
                "name",
                "icon",
                "type",
                "last_message_id",
                "guild_id",
                "parent_id",
                "owner_id",
                "last_pin_timestamp",
                "default_auto_archive_duration",
                "position",
                "permission_overwrites",
                "video_quality_mode",
                "bitrate",
                "user_limit",
                "nsfw",
                "rate_limit_per_user",
                "topic",
                "retention_policy_id",
                "flags",
                "default_thread_rate_limit_per_user"
            FROM "temporary_channels"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_channels"
        `);
        await queryRunner.query(`
            ALTER TABLE "user_settings"
                RENAME TO "temporary_user_settings"
        `);
        await queryRunner.query(`
            CREATE TABLE "user_settings" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_timeout" integer,
                "allow_accessibility_detection" boolean,
                "animate_emoji" boolean,
                "animate_stickers" integer,
                "contact_sync_enabled" boolean,
                "convert_emoticons" boolean,
                "custom_status" text,
                "default_guilds_restricted" boolean,
                "detect_platform_accounts" boolean,
                "developer_mode" boolean,
                "disable_games_tab" boolean,
                "enable_tts_command" boolean,
                "explicit_content_filter" integer,
                "friend_source_flags" text,
                "gateway_connected" boolean,
                "gif_auto_play" boolean,
                "guild_folders" text,
                "guild_positions" text,
                "inline_attachment_media" boolean,
                "inline_embed_media" boolean,
                "locale" varchar,
                "message_display_compact" boolean,
                "native_phone_integration_enabled" boolean,
                "render_embeds" boolean,
                "render_reactions" boolean,
                "restricted_guilds" text,
                "show_current_game" boolean,
                "status" varchar,
                "stream_notifications_enabled" boolean,
                "theme" varchar,
                "timezone_offset" integer,
                "friend_discovery_flags" integer NOT NULL,
                "view_nsfw_guilds" boolean NOT NULL,
                "passwordless" boolean NOT NULL
            )
        `);
        await queryRunner.query(`
            INSERT INTO "user_settings"(
                    "id",
                    "afk_timeout",
                    "allow_accessibility_detection",
                    "animate_emoji",
                    "animate_stickers",
                    "contact_sync_enabled",
                    "convert_emoticons",
                    "custom_status",
                    "default_guilds_restricted",
                    "detect_platform_accounts",
                    "developer_mode",
                    "disable_games_tab",
                    "enable_tts_command",
                    "explicit_content_filter",
                    "friend_source_flags",
                    "gateway_connected",
                    "gif_auto_play",
                    "guild_folders",
                    "guild_positions",
                    "inline_attachment_media",
                    "inline_embed_media",
                    "locale",
                    "message_display_compact",
                    "native_phone_integration_enabled",
                    "render_embeds",
                    "render_reactions",
                    "restricted_guilds",
                    "show_current_game",
                    "status",
                    "stream_notifications_enabled",
                    "theme",
                    "timezone_offset",
                    "friend_discovery_flags",
                    "view_nsfw_guilds",
                    "passwordless"
                )
            SELECT "id",
                "afk_timeout",
                "allow_accessibility_detection",
                "animate_emoji",
                "animate_stickers",
                "contact_sync_enabled",
                "convert_emoticons",
                "custom_status",
                "default_guilds_restricted",
                "detect_platform_accounts",
                "developer_mode",
                "disable_games_tab",
                "enable_tts_command",
                "explicit_content_filter",
                "friend_source_flags",
                "gateway_connected",
                "gif_auto_play",
                "guild_folders",
                "guild_positions",
                "inline_attachment_media",
                "inline_embed_media",
                "locale",
                "message_display_compact",
                "native_phone_integration_enabled",
                "render_embeds",
                "render_reactions",
                "restricted_guilds",
                "show_current_game",
                "status",
                "stream_notifications_enabled",
                "theme",
                "timezone_offset",
                "friend_discovery_flags",
                "view_nsfw_guilds",
                "passwordless"
            FROM "temporary_user_settings"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_user_settings"
        `);
        await queryRunner.query(`
            ALTER TABLE "guilds"
                RENAME TO "temporary_guilds"
        `);
        await queryRunner.query(`
            CREATE TABLE "guilds" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_channel_id" varchar,
                "afk_timeout" integer,
                "banner" varchar,
                "default_message_notifications" integer,
                "description" varchar,
                "discovery_splash" varchar,
                "explicit_content_filter" integer,
                "features" text NOT NULL,
                "primary_category_id" integer,
                "icon" varchar,
                "large" boolean,
                "max_members" integer,
                "max_presences" integer,
                "max_video_channel_users" integer,
                "member_count" integer,
                "presence_count" integer,
                "template_id" varchar,
                "mfa_level" integer,
                "name" varchar NOT NULL,
                "owner_id" varchar,
                "preferred_locale" varchar,
                "premium_subscription_count" integer,
                "premium_tier" integer,
                "public_updates_channel_id" varchar,
                "rules_channel_id" varchar,
                "region" varchar,
                "splash" varchar,
                "system_channel_id" varchar,
                "system_channel_flags" integer,
                "unavailable" boolean,
                "verification_level" integer,
                "welcome_screen" text NOT NULL,
                "widget_channel_id" varchar,
                "widget_enabled" boolean,
                "nsfw_level" integer,
                "nsfw" boolean,
                "parent" varchar,
                "premium_progress_bar_enabled" boolean,
                CONSTRAINT "FK_9d1d665379eefde7876a17afa99" FOREIGN KEY ("widget_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_cfc3d3ad260f8121c95b31a1fce" FOREIGN KEY ("system_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_95828668aa333460582e0ca6396" FOREIGN KEY ("rules_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_8d450b016dc8bec35f36729e4b0" FOREIGN KEY ("public_updates_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_fc1a451727e3643ca572a3bb394" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_e2a2f873a64a5cf62526de42325" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_f591a66b8019d87b0fe6c12dad6" FOREIGN KEY ("afk_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "guilds"(
                    "id",
                    "afk_channel_id",
                    "afk_timeout",
                    "banner",
                    "default_message_notifications",
                    "description",
                    "discovery_splash",
                    "explicit_content_filter",
                    "features",
                    "primary_category_id",
                    "icon",
                    "large",
                    "max_members",
                    "max_presences",
                    "max_video_channel_users",
                    "member_count",
                    "presence_count",
                    "template_id",
                    "mfa_level",
                    "name",
                    "owner_id",
                    "preferred_locale",
                    "premium_subscription_count",
                    "premium_tier",
                    "public_updates_channel_id",
                    "rules_channel_id",
                    "region",
                    "splash",
                    "system_channel_id",
                    "system_channel_flags",
                    "unavailable",
                    "verification_level",
                    "welcome_screen",
                    "widget_channel_id",
                    "widget_enabled",
                    "nsfw_level",
                    "nsfw",
                    "parent",
                    "premium_progress_bar_enabled"
                )
            SELECT "id",
                "afk_channel_id",
                "afk_timeout",
                "banner",
                "default_message_notifications",
                "description",
                "discovery_splash",
                "explicit_content_filter",
                "features",
                "primary_category_id",
                "icon",
                "large",
                "max_members",
                "max_presences",
                "max_video_channel_users",
                "member_count",
                "presence_count",
                "template_id",
                "mfa_level",
                "name",
                "owner_id",
                "preferred_locale",
                "premium_subscription_count",
                "premium_tier",
                "public_updates_channel_id",
                "rules_channel_id",
                "region",
                "splash",
                "system_channel_id",
                "system_channel_flags",
                "unavailable",
                "verification_level",
                "welcome_screen",
                "widget_channel_id",
                "widget_enabled",
                "nsfw_level",
                "nsfw",
                "parent",
                "premium_progress_bar_enabled"
            FROM "temporary_guilds"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_guilds"
        `);
        await queryRunner.query(`
            ALTER TABLE "channels"
                RENAME TO "temporary_channels"
        `);
        await queryRunner.query(`
            CREATE TABLE "channels" (
                "id" varchar PRIMARY KEY NOT NULL,
                "created_at" datetime NOT NULL,
                "name" varchar,
                "icon" text,
                "type" integer NOT NULL,
                "last_message_id" varchar,
                "guild_id" varchar,
                "parent_id" varchar,
                "owner_id" varchar,
                "last_pin_timestamp" integer,
                "default_auto_archive_duration" integer,
                "position" integer,
                "permission_overwrites" text,
                "video_quality_mode" integer,
                "bitrate" integer,
                "user_limit" integer,
                "nsfw" boolean,
                "rate_limit_per_user" integer,
                "topic" varchar,
                "retention_policy_id" varchar,
                "flags" integer,
                "default_thread_rate_limit_per_user" integer,
                CONSTRAINT "FK_c253dafe5f3a03ec00cd8fb4581" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
                CONSTRAINT "FK_3274522d14af40540b1a883fc80" FOREIGN KEY ("parent_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                CONSTRAINT "FK_3873ed438575cce703ecff4fc7b" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "channels"(
                    "id",
                    "created_at",
                    "name",
                    "icon",
                    "type",
                    "last_message_id",
                    "guild_id",
                    "parent_id",
                    "owner_id",
                    "last_pin_timestamp",
                    "default_auto_archive_duration",
                    "position",
                    "permission_overwrites",
                    "video_quality_mode",
                    "bitrate",
                    "user_limit",
                    "nsfw",
                    "rate_limit_per_user",
                    "topic",
                    "retention_policy_id",
                    "flags",
                    "default_thread_rate_limit_per_user"
                )
            SELECT "id",
                "created_at",
                "name",
                "icon",
                "type",
                "last_message_id",
                "guild_id",
                "parent_id",
                "owner_id",
                "last_pin_timestamp",
                "default_auto_archive_duration",
                "position",
                "permission_overwrites",
                "video_quality_mode",
                "bitrate",
                "user_limit",
                "nsfw",
                "rate_limit_per_user",
                "topic",
                "retention_policy_id",
                "flags",
                "default_thread_rate_limit_per_user"
            FROM "temporary_channels"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_channels"
        `);
    }

}
