import { MigrationInterface, QueryRunner } from "typeorm";

export class opencordFixes1660678573060 implements MigrationInterface {
    name = 'opencordFixes1660678573060'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "temporary_users" (
                "id" varchar PRIMARY KEY NOT NULL,
                "username" varchar NOT NULL,
                "discriminator" varchar NOT NULL,
                "avatar" varchar,
                "accent_color" integer,
                "banner" varchar,
                "phone" varchar,
                "desktop" boolean NOT NULL,
                "mobile" boolean NOT NULL,
                "premium" boolean NOT NULL,
                "premium_type" integer NOT NULL,
                "bot" boolean NOT NULL,
                "bio" varchar,
                "system" boolean NOT NULL,
                "nsfw_allowed" boolean NOT NULL,
                "mfa_enabled" boolean,
                "totp_secret" varchar,
                "totp_last_ticket" varchar,
                "created_at" datetime NOT NULL,
                "premium_since" datetime,
                "verified" boolean NOT NULL,
                "disabled" boolean NOT NULL,
                "deleted" boolean NOT NULL,
                "email" varchar,
                "flags" varchar NOT NULL,
                "public_flags" integer NOT NULL,
                "rights" bigint NOT NULL,
                "data" text NOT NULL,
                "fingerprints" text NOT NULL,
                "extended_settings" text NOT NULL,
                "notes" text NOT NULL,
                "settingsId" varchar,
                "purchased_flags" integer NOT NULL,
                "premium_usage_flags" integer NOT NULL,
                CONSTRAINT "UQ_b1dd13b6ed980004a795ca184a6" UNIQUE ("settingsId"),
                CONSTRAINT "FK_76ba283779c8441fd5ff819c8cf" FOREIGN KEY ("settingsId") REFERENCES "user_settings" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_users"(
                    "id",
                    "username",
                    "discriminator",
                    "avatar",
                    "accent_color",
                    "banner",
                    "phone",
                    "desktop",
                    "mobile",
                    "premium",
                    "premium_type",
                    "bot",
                    "bio",
                    "system",
                    "nsfw_allowed",
                    "mfa_enabled",
                    "totp_secret",
                    "totp_last_ticket",
                    "created_at",
                    "premium_since",
                    "verified",
                    "disabled",
                    "deleted",
                    "email",
                    "flags",
                    "public_flags",
                    "rights",
                    "data",
                    "fingerprints",
                    "extended_settings",
                    "notes",
                    "settingsId"
                )
            SELECT "id",
                "username",
                "discriminator",
                "avatar",
                "accent_color",
                "banner",
                "phone",
                "desktop",
                "mobile",
                "premium",
                "premium_type",
                "bot",
                "bio",
                "system",
                "nsfw_allowed",
                "mfa_enabled",
                "totp_secret",
                "totp_last_ticket",
                "created_at",
                "premium_since",
                "verified",
                "disabled",
                "deleted",
                "email",
                "flags",
                "public_flags",
                "rights",
                "data",
                "fingerprints",
                "extended_settings",
                "notes",
                "settingsId"
            FROM "users"
        `);
        await queryRunner.query(`
            DROP TABLE "users"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_users"
                RENAME TO "users"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_user_settings" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_timeout" integer,
                "allow_accessibility_detection" boolean,
                "animate_emoji" boolean,
                "animate_stickers" integer,
                "contact_sync_enabled" boolean,
                "convert_emoticons" boolean,
                "custom_status" text,
                "default_guilds_restricted" boolean,
                "detect_platform_accounts" boolean,
                "developer_mode" boolean,
                "disable_games_tab" boolean,
                "enable_tts_command" boolean,
                "explicit_content_filter" integer,
                "friend_source_flags" text,
                "gateway_connected" boolean,
                "gif_auto_play" boolean,
                "guild_folders" text,
                "guild_positions" text,
                "inline_attachment_media" boolean,
                "inline_embed_media" boolean,
                "locale" varchar,
                "message_display_compact" boolean,
                "native_phone_integration_enabled" boolean,
                "render_embeds" boolean,
                "render_reactions" boolean,
                "restricted_guilds" text,
                "show_current_game" boolean,
                "status" varchar,
                "stream_notifications_enabled" boolean,
                "theme" varchar,
                "timezone_offset" integer,
                "friend_discovery_flags" integer NOT NULL,
                "view_nsfw_guilds" boolean NOT NULL,
                "passwordless" boolean NOT NULL
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_user_settings"(
                    "id",
                    "afk_timeout",
                    "allow_accessibility_detection",
                    "animate_emoji",
                    "animate_stickers",
                    "contact_sync_enabled",
                    "convert_emoticons",
                    "custom_status",
                    "default_guilds_restricted",
                    "detect_platform_accounts",
                    "developer_mode",
                    "disable_games_tab",
                    "enable_tts_command",
                    "explicit_content_filter",
                    "friend_source_flags",
                    "gateway_connected",
                    "gif_auto_play",
                    "guild_folders",
                    "guild_positions",
                    "inline_attachment_media",
                    "inline_embed_media",
                    "locale",
                    "message_display_compact",
                    "native_phone_integration_enabled",
                    "render_embeds",
                    "render_reactions",
                    "restricted_guilds",
                    "show_current_game",
                    "status",
                    "stream_notifications_enabled",
                    "theme",
                    "timezone_offset"
                )
            SELECT "id",
                "afk_timeout",
                "allow_accessibility_detection",
                "animate_emoji",
                "animate_stickers",
                "contact_sync_enabled",
                "convert_emoticons",
                "custom_status",
                "default_guilds_restricted",
                "detect_platform_accounts",
                "developer_mode",
                "disable_games_tab",
                "enable_tts_command",
                "explicit_content_filter",
                "friend_source_flags",
                "gateway_connected",
                "gif_auto_play",
                "guild_folders",
                "guild_positions",
                "inline_attachment_media",
                "inline_embed_media",
                "locale",
                "message_display_compact",
                "native_phone_integration_enabled",
                "render_embeds",
                "render_reactions",
                "restricted_guilds",
                "show_current_game",
                "status",
                "stream_notifications_enabled",
                "theme",
                "timezone_offset"
            FROM "user_settings"
        `);
        await queryRunner.query(`
            DROP TABLE "user_settings"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_user_settings"
                RENAME TO "user_settings"
        `);
        await queryRunner.query(`
            CREATE TABLE "temporary_users" (
                "id" varchar PRIMARY KEY NOT NULL,
                "username" varchar NOT NULL,
                "discriminator" varchar NOT NULL,
                "avatar" varchar,
                "accent_color" integer,
                "banner" varchar,
                "phone" varchar,
                "desktop" boolean NOT NULL,
                "mobile" boolean NOT NULL,
                "premium" boolean NOT NULL,
                "premium_type" integer NOT NULL,
                "bot" boolean NOT NULL,
                "bio" varchar,
                "system" boolean NOT NULL,
                "nsfw_allowed" boolean NOT NULL,
                "mfa_enabled" boolean NOT NULL,
                "totp_secret" varchar,
                "totp_last_ticket" varchar,
                "created_at" datetime NOT NULL,
                "premium_since" datetime,
                "verified" boolean NOT NULL,
                "disabled" boolean NOT NULL,
                "deleted" boolean NOT NULL,
                "email" varchar,
                "flags" varchar NOT NULL,
                "public_flags" integer NOT NULL,
                "rights" bigint NOT NULL,
                "data" text NOT NULL,
                "fingerprints" text NOT NULL,
                "extended_settings" text NOT NULL,
                "notes" text NOT NULL,
                "settingsId" varchar,
                "purchased_flags" integer NOT NULL,
                "premium_usage_flags" integer NOT NULL,
                CONSTRAINT "UQ_b1dd13b6ed980004a795ca184a6" UNIQUE ("settingsId"),
                CONSTRAINT "FK_76ba283779c8441fd5ff819c8cf" FOREIGN KEY ("settingsId") REFERENCES "user_settings" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "temporary_users"(
                    "id",
                    "username",
                    "discriminator",
                    "avatar",
                    "accent_color",
                    "banner",
                    "phone",
                    "desktop",
                    "mobile",
                    "premium",
                    "premium_type",
                    "bot",
                    "bio",
                    "system",
                    "nsfw_allowed",
                    "mfa_enabled",
                    "totp_secret",
                    "totp_last_ticket",
                    "created_at",
                    "premium_since",
                    "verified",
                    "disabled",
                    "deleted",
                    "email",
                    "flags",
                    "public_flags",
                    "rights",
                    "data",
                    "fingerprints",
                    "extended_settings",
                    "notes",
                    "settingsId",
                    "purchased_flags",
                    "premium_usage_flags"
                )
            SELECT "id",
                "username",
                "discriminator",
                "avatar",
                "accent_color",
                "banner",
                "phone",
                "desktop",
                "mobile",
                "premium",
                "premium_type",
                "bot",
                "bio",
                "system",
                "nsfw_allowed",
                "mfa_enabled",
                "totp_secret",
                "totp_last_ticket",
                "created_at",
                "premium_since",
                "verified",
                "disabled",
                "deleted",
                "email",
                "flags",
                "public_flags",
                "rights",
                "data",
                "fingerprints",
                "extended_settings",
                "notes",
                "settingsId",
                "purchased_flags",
                "premium_usage_flags"
            FROM "users"
        `);
        await queryRunner.query(`
            DROP TABLE "users"
        `);
        await queryRunner.query(`
            ALTER TABLE "temporary_users"
                RENAME TO "users"
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "users"
                RENAME TO "temporary_users"
        `);
        await queryRunner.query(`
            CREATE TABLE "users" (
                "id" varchar PRIMARY KEY NOT NULL,
                "username" varchar NOT NULL,
                "discriminator" varchar NOT NULL,
                "avatar" varchar,
                "accent_color" integer,
                "banner" varchar,
                "phone" varchar,
                "desktop" boolean NOT NULL,
                "mobile" boolean NOT NULL,
                "premium" boolean NOT NULL,
                "premium_type" integer NOT NULL,
                "bot" boolean NOT NULL,
                "bio" varchar,
                "system" boolean NOT NULL,
                "nsfw_allowed" boolean NOT NULL,
                "mfa_enabled" boolean,
                "totp_secret" varchar,
                "totp_last_ticket" varchar,
                "created_at" datetime NOT NULL,
                "premium_since" datetime,
                "verified" boolean NOT NULL,
                "disabled" boolean NOT NULL,
                "deleted" boolean NOT NULL,
                "email" varchar,
                "flags" varchar NOT NULL,
                "public_flags" integer NOT NULL,
                "rights" bigint NOT NULL,
                "data" text NOT NULL,
                "fingerprints" text NOT NULL,
                "extended_settings" text NOT NULL,
                "notes" text NOT NULL,
                "settingsId" varchar,
                "purchased_flags" integer NOT NULL,
                "premium_usage_flags" integer NOT NULL,
                CONSTRAINT "UQ_b1dd13b6ed980004a795ca184a6" UNIQUE ("settingsId"),
                CONSTRAINT "FK_76ba283779c8441fd5ff819c8cf" FOREIGN KEY ("settingsId") REFERENCES "user_settings" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "users"(
                    "id",
                    "username",
                    "discriminator",
                    "avatar",
                    "accent_color",
                    "banner",
                    "phone",
                    "desktop",
                    "mobile",
                    "premium",
                    "premium_type",
                    "bot",
                    "bio",
                    "system",
                    "nsfw_allowed",
                    "mfa_enabled",
                    "totp_secret",
                    "totp_last_ticket",
                    "created_at",
                    "premium_since",
                    "verified",
                    "disabled",
                    "deleted",
                    "email",
                    "flags",
                    "public_flags",
                    "rights",
                    "data",
                    "fingerprints",
                    "extended_settings",
                    "notes",
                    "settingsId",
                    "purchased_flags",
                    "premium_usage_flags"
                )
            SELECT "id",
                "username",
                "discriminator",
                "avatar",
                "accent_color",
                "banner",
                "phone",
                "desktop",
                "mobile",
                "premium",
                "premium_type",
                "bot",
                "bio",
                "system",
                "nsfw_allowed",
                "mfa_enabled",
                "totp_secret",
                "totp_last_ticket",
                "created_at",
                "premium_since",
                "verified",
                "disabled",
                "deleted",
                "email",
                "flags",
                "public_flags",
                "rights",
                "data",
                "fingerprints",
                "extended_settings",
                "notes",
                "settingsId",
                "purchased_flags",
                "premium_usage_flags"
            FROM "temporary_users"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_users"
        `);
        await queryRunner.query(`
            ALTER TABLE "user_settings"
                RENAME TO "temporary_user_settings"
        `);
        await queryRunner.query(`
            CREATE TABLE "user_settings" (
                "id" varchar PRIMARY KEY NOT NULL,
                "afk_timeout" integer,
                "allow_accessibility_detection" boolean,
                "animate_emoji" boolean,
                "animate_stickers" integer,
                "contact_sync_enabled" boolean,
                "convert_emoticons" boolean,
                "custom_status" text,
                "default_guilds_restricted" boolean,
                "detect_platform_accounts" boolean,
                "developer_mode" boolean,
                "disable_games_tab" boolean,
                "enable_tts_command" boolean,
                "explicit_content_filter" integer,
                "friend_source_flags" text,
                "gateway_connected" boolean,
                "gif_auto_play" boolean,
                "guild_folders" text,
                "guild_positions" text,
                "inline_attachment_media" boolean,
                "inline_embed_media" boolean,
                "locale" varchar,
                "message_display_compact" boolean,
                "native_phone_integration_enabled" boolean,
                "render_embeds" boolean,
                "render_reactions" boolean,
                "restricted_guilds" text,
                "show_current_game" boolean,
                "status" varchar,
                "stream_notifications_enabled" boolean,
                "theme" varchar,
                "timezone_offset" integer
            )
        `);
        await queryRunner.query(`
            INSERT INTO "user_settings"(
                    "id",
                    "afk_timeout",
                    "allow_accessibility_detection",
                    "animate_emoji",
                    "animate_stickers",
                    "contact_sync_enabled",
                    "convert_emoticons",
                    "custom_status",
                    "default_guilds_restricted",
                    "detect_platform_accounts",
                    "developer_mode",
                    "disable_games_tab",
                    "enable_tts_command",
                    "explicit_content_filter",
                    "friend_source_flags",
                    "gateway_connected",
                    "gif_auto_play",
                    "guild_folders",
                    "guild_positions",
                    "inline_attachment_media",
                    "inline_embed_media",
                    "locale",
                    "message_display_compact",
                    "native_phone_integration_enabled",
                    "render_embeds",
                    "render_reactions",
                    "restricted_guilds",
                    "show_current_game",
                    "status",
                    "stream_notifications_enabled",
                    "theme",
                    "timezone_offset"
                )
            SELECT "id",
                "afk_timeout",
                "allow_accessibility_detection",
                "animate_emoji",
                "animate_stickers",
                "contact_sync_enabled",
                "convert_emoticons",
                "custom_status",
                "default_guilds_restricted",
                "detect_platform_accounts",
                "developer_mode",
                "disable_games_tab",
                "enable_tts_command",
                "explicit_content_filter",
                "friend_source_flags",
                "gateway_connected",
                "gif_auto_play",
                "guild_folders",
                "guild_positions",
                "inline_attachment_media",
                "inline_embed_media",
                "locale",
                "message_display_compact",
                "native_phone_integration_enabled",
                "render_embeds",
                "render_reactions",
                "restricted_guilds",
                "show_current_game",
                "status",
                "stream_notifications_enabled",
                "theme",
                "timezone_offset"
            FROM "temporary_user_settings"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_user_settings"
        `);
        await queryRunner.query(`
            ALTER TABLE "users"
                RENAME TO "temporary_users"
        `);
        await queryRunner.query(`
            CREATE TABLE "users" (
                "id" varchar PRIMARY KEY NOT NULL,
                "username" varchar NOT NULL,
                "discriminator" varchar NOT NULL,
                "avatar" varchar,
                "accent_color" integer,
                "banner" varchar,
                "phone" varchar,
                "desktop" boolean NOT NULL,
                "mobile" boolean NOT NULL,
                "premium" boolean NOT NULL,
                "premium_type" integer NOT NULL,
                "bot" boolean NOT NULL,
                "bio" varchar,
                "system" boolean NOT NULL,
                "nsfw_allowed" boolean NOT NULL,
                "mfa_enabled" boolean,
                "totp_secret" varchar,
                "totp_last_ticket" varchar,
                "created_at" datetime NOT NULL,
                "premium_since" datetime,
                "verified" boolean NOT NULL,
                "disabled" boolean NOT NULL,
                "deleted" boolean NOT NULL,
                "email" varchar,
                "flags" varchar NOT NULL,
                "public_flags" integer NOT NULL,
                "rights" bigint NOT NULL,
                "data" text NOT NULL,
                "fingerprints" text NOT NULL,
                "extended_settings" text NOT NULL,
                "notes" text NOT NULL,
                "settingsId" varchar,
                CONSTRAINT "UQ_b1dd13b6ed980004a795ca184a6" UNIQUE ("settingsId"),
                CONSTRAINT "FK_76ba283779c8441fd5ff819c8cf" FOREIGN KEY ("settingsId") REFERENCES "user_settings" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
        await queryRunner.query(`
            INSERT INTO "users"(
                    "id",
                    "username",
                    "discriminator",
                    "avatar",
                    "accent_color",
                    "banner",
                    "phone",
                    "desktop",
                    "mobile",
                    "premium",
                    "premium_type",
                    "bot",
                    "bio",
                    "system",
                    "nsfw_allowed",
                    "mfa_enabled",
                    "totp_secret",
                    "totp_last_ticket",
                    "created_at",
                    "premium_since",
                    "verified",
                    "disabled",
                    "deleted",
                    "email",
                    "flags",
                    "public_flags",
                    "rights",
                    "data",
                    "fingerprints",
                    "extended_settings",
                    "notes",
                    "settingsId"
                )
            SELECT "id",
                "username",
                "discriminator",
                "avatar",
                "accent_color",
                "banner",
                "phone",
                "desktop",
                "mobile",
                "premium",
                "premium_type",
                "bot",
                "bio",
                "system",
                "nsfw_allowed",
                "mfa_enabled",
                "totp_secret",
                "totp_last_ticket",
                "created_at",
                "premium_since",
                "verified",
                "disabled",
                "deleted",
                "email",
                "flags",
                "public_flags",
                "rights",
                "data",
                "fingerprints",
                "extended_settings",
                "notes",
                "settingsId"
            FROM "temporary_users"
        `);
        await queryRunner.query(`
            DROP TABLE "temporary_users"
        `);
    }

}
