name: Nix build

on:
  push:
  pull_request:

jobs:
  build-nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-bincache.rory.gay:663PIW8xxgIImxLcsokODWI2PHFWXvzJEfjX6TaIjxQ=
          trusted-substituters = https://cache.nixos.org https://nix-bincache.rory.gay

    - run: nix build -L -j auto
    - run: nix develop --command echo OK
    - run: nix flake check -vL -j auto
